In [1]:
import numpy as np

In [2]:
import numpy.linalg as npla

In [5]:
X = np.round(np.random.rand(2,2))

In [6]:
print(X)

[[0. 0.]
 [0. 0.]]


In [7]:
X = np.array([[4, -1],[-1, 4]])

In [8]:
print(X)

[[ 4 -1]
 [-1  4]]


In [9]:
print(npla.eig(X))

(array([5., 3.]), array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))
