In [1]:
import numpy as np

In [2]:
import numpy.linalg as la

In [3]:
a = np.diag(range(1,5))

In [4]:
p = np.round(10*np.random.rand(4,4))

In [5]:
print(p)

[[1. 2. 2. 2.]
 [2. 1. 5. 6.]
 [2. 8. 9. 1.]
 [4. 5. 5. 6.]]


In [6]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [7]:
print(p@a)

[[ 1.  4.  6.  8.]
 [ 2.  2. 15. 24.]
 [ 2. 16. 27.  4.]
 [ 4. 10. 15. 24.]]


In [8]:
print(a@p)

[[ 1.  2.  2.  2.]
 [ 4.  2. 10. 12.]
 [ 6. 24. 27.  3.]
 [16. 20. 20. 24.]]


In [9]:
v = np.array([3, 0, 2, 1])

In [10]:
print(a[v,:])

[[0 0 0 4]
 [1 0 0 0]
 [0 0 3 0]
 [0 2 0 0]]


In [11]:
print(a[:,v])

[[0 1 0 0]
 [0 0 0 2]
 [0 0 3 0]
 [4 0 0 0]]


In [17]:
print(a[:,v]@p)

[[ 2.  1.  5.  6.]
 [ 8. 10. 10. 12.]
 [ 6. 24. 27.  3.]
 [ 4.  8.  8.  8.]]


In [13]:
def LUfactorNoPiv(A):
    m,n = A.shape
    assert m==n, "A should be a square matrix"
    L = np.eye(n)
    for row in range(1, n):
        for col in range(row):
            mul = A[row, col]/A[col, col]
            A[row, :]-=mul*A[col, :]
            print(mul)
            L[row,col] = mul
            print("L=",L[row,col])
    U = np.triu(A)
            #L = np.round(A-U+np.eye(n),3)
    return (A,L)

In [14]:
k = 1.0*np.array([[5,-1,-1],[-1,5,-1],[-1,-1,5]])

In [15]:
A = LUfactorNoPiv(k)

-0.2
L= -0.2
-0.2
L= -0.2
-0.25
L= -0.25


In [16]:
print(A[0],"\n\n", A[1])

[[ 5.  -1.  -1. ]
 [ 0.   4.8 -1.2]
 [ 0.   0.   4.5]] 

 [[ 1.    0.    0.  ]
 [-0.2   1.    0.  ]
 [-0.2  -0.25  1.  ]]
